<a href="https://colab.research.google.com/github/ninetales2002/skills-introduction-to-github/blob/main/practica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def magiCuadrado(n):
  # Esto es puramente con fines declarativos, podría directamente llamar a la función con los valores y listo
  c= np.zeros((n, n))
  N = [x + 1 for x in list(range(n**2))]
  i= 0
  j= 0
  nm= 0
  #suma= 0

  return magiCuad(n, i, j, N, c, 0)

def diag1_val(c):
  suma= 0
  for i in range(len(c)):
    suma += c[i][i]
  return suma == sum(c[0])

def diag2_val(c):
  suma= 0
  n= len(c)
  for i in range(len(c)):
    suma += c[i][n-1-i]
  return suma == sum(c[0])

def fila_val(c, i):
  return sum(c[i])== sum(c[0])

def col_val(c, j):
  return sum(c[:, j])== sum(c[0])

def magiCuad(n, i, j, N, c, suma):

  if i==(n-1) and j==(n-1):   # si llego al último casillero
    c_l = c.copy()
    c_l[i][j] = N[0]

    if (fila_val(c_l, i) and col_val(c_l, j)): # and diag1_val(c) and diag2_val(c)):   chequeo que tanto la última fila como columna de el número mágico, y las dos diagonales
      print("Success! :D")
      print(c_l)
      return 1   # es cuadrado mágico!
    else:
      return 0   # F

  elif i==(n-1):   # si estoy por llenar una nueva columna:
    for l in range(len(N)):
      n_l = N.copy()
      c_l = c.copy()
      c_l[i][j] = n_l[l]
      n_l.pop(l)
      if col_val(c_l, j):  # si la suma de la columna me da, sigo
        #if j==0:  # si es la primera columna que lleno, ya puedo fijarme si una de las diagonales da el número mágico, si no lo hace descarto
        #  if not diag2_val(c):
        #    return 0
        suma+= magiCuad(n, i, j+1, n_l, c_l, suma)
      else:
        #print("F")
        # print(c_l)
        return 0    # la suma de la columna no me dió, descarto

  elif j==(n-1):  # si estoy por llenar otra fila
    for l in range(len(N)):
      n_l = N.copy()
      c_l = c.copy()
      c_l[i][j] = n_l[l]
      n_l.pop(l)
      if i==0 or fila_val(c_l, i):
        suma+= magiCuad(n, i+1, 0, n_l, c_l, suma)  # puede ser solución parcial, sigo sumando en la siguiente fila
      else:
        return 0  # ya sé que no es solución parcial, descarto (o sea, no la sumo ni la sigo llenando)

  else:    # si no se completó nada, sigo no más
    for l in range(len(N)):
        n_l = N.copy()
        c_l = c.copy()
        c_l[i][j] = n_l[l]
        n_l.pop(l)
        suma+= magiCuad(n, i, j+1, n_l, c_l, suma)

  return suma


In [ ]:
c_magico = np.array([[2,7,6], [9,5,1], [4,3,8]])

nm= 15

print(diag2_val(c_magico))

True


In [ ]:
print(magiCuadrado(3))

Success! :D
[[7. 2. 6.]
 [5. 9. 1.]
 [3. 4. 8.]]
Success! :D
[[7. 3. 5.]
 [6. 8. 1.]
 [2. 4. 9.]]
Success! :D
[[8. 1. 6.]
 [4. 9. 2.]
 [3. 5. 7.]]
0


##RutaMinima

4. Dada una matriz D de n × n números naturales, queremos encontrar una permutación π1 de
{1, . . . , n} que minimice Dπ(n)π(1) + Pn−1
i=1 Dπ(i)π(i+1). Por ejemplo, si


\\[
D = \begin{bmatrix}
0 1 10 10 \\
10 0 3 15\\
21 17 0 2 \\
3 22 30 0 \\
\end{bmatrix}
\]\


entonces π(i) = i es una solución optima.

a) Diseñar un algoritmo de backtracking para resolver el problema, indicando claramente cómo
se codifica una solución candidata, cuáles soluciones son válidas y qué valor tienen, qué es
una solución parcial y cómo se extiende cada solución parcial.

b) Calcular la complejidad temporal y espacial del mismo.

c) Proponer una poda por optimalidad y mostrar que es correcta.

In [ ]:
import numpy as np

# Inicializo a estas dos variables por fuera de las funciones para que se pueda acceder a ellas independientemente del llamado de la función (quizás existe una mejor forma)
best_pi_ruta = 1000000000000000000000 # pongo un número muy alto como para que el primer candidato siempre lo supere (quizás existe una mejor forma)
best_pi = []

D = np.array([[0, 1, 10, 10],
              [10, 0, 3, 15],
              [21, 17, 0, 2],
              [3, 22, 30, 0]])

def calculoRuta(D, pi, n):
  sum= 0
  for i in range(n-1):                 # = D[n][0] + D[0][1] + D[1][2] + D[2][3] + ... + D[n-1][n]
    sum += D[pi[i]][pi[i+1]]

  if n== len(D):
    return D[n-1][0] + sum
  else:
    return sum

def rutaMínima(D):
  n = len(D)

  # N es el conjunto de números naturales que conforman los índices de la matriz D
  N = list(range(n))

  rutaMinimaAux(D, N, [])

  print(best_pi)

def rutaMinimaAux(D, N, pi):
  global best_pi_ruta, best_pi
  if len(N)==0:
    pi_ruta = calculoRuta(D, pi, len(pi))
    if pi_ruta < best_pi_ruta:
      best_pi_ruta = pi_ruta
      best_pi = pi
      print("Nueva mejor permutación: ", best_pi)

    # Poda: me fijo que la suma parcial de la matriz generada con los índices que ya asigné no me supere
    # el best_pi_ruta
    # Esto es posible porque voy asignando los índices de D de 0 a n, en orden, de manera que siempre tengo
    # definida la submatriz superior izquierda de tamaño k = len(pi).

  elif calculoRuta(D, pi, len(pi))< best_pi_ruta:
    for i in range(len(N)):
      N_copia = N.copy()
      elem = N_copia.pop(i)
      pi_copia = pi.copy()
      pi_copia.append(elem)
      rutaMinimaAux(D, N_copia, pi_copia)

rutaMínima(D)



Nueva mejor permutación:  [0, 1, 2, 3]
[0, 1, 2, 3]


    # elijo el próximo índice seleccionando el mínimo entre los resultados posibles
    # (pero no terminaría ejecutando todas las recursiones de todos modos para poder
    # averiguar ese mínimo? Creo que eso sería más bien programación dinámica)
    # Genero la permutación sumando el siguiente

In [ ]:
# Ej 5: OptiPago

# Con backtracking

# La defino con un "límite de exceso" que me permita establecer cuándo
# optar por una opción con menos billetes a pesar de que el exceso sea
# mayor


def optiPagoBack(B, c, max_exc):
  best_c = float('inf')  # esta variable tiene valor <=0 y representa el mínimo exceso de pago
  best_q = float('inf')  # mejor mínima cantidad de billetes.

  def optiPagoBackAux(B, i, c_aux, q, max_exc):
    #nonlocal best_c, best_q
    if c_aux <= 0 :
      if q < best_q and c_aux >= -max_exc :
        best_c = c_aux
        best_q = q
      elif q == best_q and c_aux > best_c:
        best_c = c_aux

    elif i < len(B):
      optiPagoBackAux(B, i+1, c_aux-B[i], q+1, max_exc)
      optiPagoBackAux(B, i+1, c_aux, q, max_exc)

  optiPagoBackAux(B, 0, c, 0, max_exc)

  return (c-best_c, best_q)

B = [2,3,5,10,20,20]
c= 14

optiPagoBack(B, c, 1)

# La complejidad (sin considerar la poda) es todas las llamadas realizadas,
# que corresponde a todos los subconjuntos posibles de B.
# Para cada billete b_i de B existe la posibilidad de que b_i esté en el
# subconjunto o no lo esté, por lo tanto por cada elemento del conjunto se
# duplica la cantidad de llamados.
# Luego # conjuntos = 2^|B| --> O(2^|B|)


UnboundLocalError: local variable 'best_q' referenced before assignment

In [ ]:
# Ej 5: OptiPago

# Con backtracking

# La defino con un "límite de exceso" que me permita establecer cuándo
# optar por una opción con menos billetes a pesar de que el exceso sea
# mayor


repetidos = {}

def optiPagoBack(B, c, max_exc):
  best_c = float('inf')  # esta variable tiene valor <=0 y representa el mínimo exceso de pago
  best_q = float('inf')  # mejor mínima cantidad de billetes.

  def optiPagoBackAux(B, i, c_aux, q, max_exc):
    nonlocal best_c, best_q
    if c_aux <= 0 :
      if q < best_q and c_aux >= -max_exc :
        best_c = c_aux
        best_q = q
      elif q == best_q and c_aux > best_c:
        best_c = c_aux

    elif i < len(B):
      #print("Voy a llamar con i={}, c_aux={}".format(i+1, c_aux-B[i]))
      optiPagoBackAux(B, i+1, c_aux-B[i], q+1, max_exc)
      #print("Voy a llamar con i={}, c_aux={}".format(i+1, c_aux))
      optiPagoBackAux(B, i+1, c_aux, q, max_exc)

      # Check if the key exists in the dictionary
      key1= str((i+1, c_aux-B[i]))
      key2= str((i+1, c_aux))
      if key1 in repetidos:
          # If it exists, increment its value by 1
          repetidos[key1] += 1
      else:
          # If it doesn't exist, assign a value of 1 to it
          repetidos[key1]  = 1

      if key2 in repetidos:
          # If it exists, increment its value by 1
          repetidos[key2] += 1
      else:
          # If it doesn't exist, assign a value of 1 to it
          repetidos[key2]  = 1


  optiPagoBackAux(B, 0, c, 0, max_exc)

  return (c-best_c, best_q)

B = [2,3,5,10,20,20]
c= 14

optiPagoBack(B, c, 6)

import pandas as pd
repe= pd.DataFrame(repetidos.items(), columns= ["Entrada", "n° llamados"])

# Como se puede ver en el dataframe, hay muchos pares de datos
# de entrada que se repiten

repe

Entrada  n° llamados
0   (6, -16)            2
1     (6, 4)            2
2   (5, -16)            2
3     (5, 4)            2
4    (4, -6)            1
..       ...          ...
57   (3, 14)            1
58   (2, 11)            1
59   (2, 14)            1
60   (1, 12)            1
61   (1, 14)            1

[62 rows x 2 columns]

In [ ]:
import numpy as np
import pandas as pd

# La estructura va a ser una matriz de |B| x (c+1), donde i va a representar
# al billete i con el que se está llamando a la función y (c+1) el monto que va
# quedando por pagar.


def optiPagoMemo(B, c, max_exc):
  n = len(B)
  M = np.zeros((n+1, c+1))


  def optiPagoBackAux(B, i, c_aux, max_exc):
    #nonlocal M

    if i < len(B) and B[i] < c_aux:
      if M[i+1][c_aux-B[i]]==0:
        M[i+1][c_aux-B[i]]= optiPagoBackAux(B, i+1, c_aux-B[i], max_exc)
        #print(M[i+1, c_aux-B[i]])

      if M[i+1][c_aux]==0:
        M[i+1][c_aux]= optiPagoBackAux(B, i+1, c_aux, max_exc)
        #print(M[i+1, c_aux])

      return min(1 + M[i+1][c_aux-B[i]], M[i+1][c_aux])

    elif i== len(B):
      return 0

    # casos base: sumando el próximo billete te pasás (lo tengo que poner aparte porque no lo puedo incluir en la matriz)

    elif c_aux-B[i] >= -max_exc:    # caso 1: te quedás dentro del rango tolerado conservás la opción y lo sumás
      return 1

    else:    # caso 2 : te pasaste del exceso tolerado, descartás la solución
      return float('inf')


  print(optiPagoBackAux(B, 0, c, max_exc))
  M= pd.DataFrame(M, columns= list(range(c+1)), index= [0] + B)
  return M


B = [2,3,5,10,20,20]

c= 14

optiPagoMemo(B, c, 1)

2.0


0    1    2    3    4    5    6    7    8    9    10   11   12   13   14
0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  2.0  0.0  2.0
3   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  inf  inf  0.0  2.0
5   0.0  0.0  0.0  0.0  inf  0.0  inf  inf  0.0  1.0  0.0  inf  inf  0.0  inf
10  0.0  inf  inf  0.0  inf  0.0  0.0  0.0  0.0  0.0  0.0  inf  inf  0.0  inf
20  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
20  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

#AstroTrade
7. Astro Void se dedica a la compra de asteroides. Sea p ∈ N
n
tal que pi es el precio de un asteroide
el i-ésimo día en una secuencia de n días. Astro Void quiere comprar y vender asteroides durante
esos n días de manera tal de obtener la mayor ganancia neta posible. Debido a las dificultades
que existen en el transporte y almacenamiento de asteroides, Astro Void puede comprar a lo
sumo un asteroide cada día, puede vender a lo sumo un asteroide cada día y comienza sin
asteroides. Además, el Ente Regulador Asteroidal impide que Astro Void venda un asteroide
que no haya comprado. Queremos encontrar la máxima ganancia neta que puede obtener Astro
Void respetando las restricciones indicadas. Por ejemplo, si p = (3, 2, 5, 6) el resultado es 6 y si
p = (3, 6, 10) el resultado es 7. Notar que en una solución óptima, Astro Void debe terminar sin
asteroides.

a) Convencerse de que la máxima ganancia neta (m.g.n.), si Astro Void tiene c asteroides al
fin del día j, es:
indefinido (i.e., −∞) si c < 0 o c > j, o
el máximo entre:
• la m.g.n. de finalizar el día j − 1 con c − 1 asteroides y comprar uno en el día j,
• la m.g.n. de finalizar el día j − 1 con c + 1 asteroides y vender uno en el día j,
• la m.g.n. de finalizar el día j − 1 con c asteroides y no operar el día j.

b) Escribir matemáticamente la formulación recursiva enunciada en a). Dar los valores de los
casos base en función de la restricción de que comienza sin asteroides.

c) Indicar qué dato es la respuesta al problema con esa formulación recursiva.

d) Diseñar un algoritmo de PD top-down que resuelva el problema y explicar su complejidad
temporal y espacial auxiliar.

e) (Opcional) Diseñar un algoritmo de PD bottom-up, reduciendo la complejidad espacial.

f) (Opcional) Formalmente, el problema consiste en determinar el máximo g =
Pn
i=1 xipi para
un vector x = (x1, . . . , xn) tal que: xi ∈ {−1, 0, 1} para todo 1 ≤ i ≤ n y
Pj
i=1 xi ≥ 0
para todo 1 ≤ j ≤ n. Demostrar que la formulacion recursiva es correcta. Ayuda: primero
demostrar que existe una solución óptima en la que Astro Void se queda sin asteroides en
el día n. Luego, demostrar por inducción que la función recursiva respeta la semántica, i.e.,
que computa la m.g.n. al final del día j cuando Astro Void posee c asteroides.

---
a) (Analizando la función dada)

- Es indefinido si c < 0 porque no se puede tener cantidad de asteroides negativa.
- Es indefinido si c > j porque solo se puede comprar máximo un asteroide al día. Por lo tanto no puede ser que por ejemplo hayan pasado 3 días (j=3) y se tengan 4 asteroides al final del 3er día.

Sino es el máximo entre:

- mgn de haber comprado un asteroide en el día j
- mgn de haber vendido un asteroide en el día j
 mgn de no haber vendido ni comprado nada en el día j, es decir, mantener los mismos asteroides en j-1 y j

La recursión se dar del último día hasta el primero/los primeros. Es tipo top-down.

In [ ]:
def astroVoid(precios):
  n_dias = len(precios)

  def astroVoidAux(j, c):
    nonlocal precios
    if c < 0 or c > j+1:
      return -float('inf')

    elif j==0:
      if c==1:
        return - precios[j]
      else:
        return 0

    else:
      ganancia_comprando= astroVoidAux(j-1, c-1) - precios[j]    # resto p[j] por el coste del asteroide comprado
      ganancia_vendiendo= astroVoidAux(j-1, c+1) + precios[j]    # sumo p[j] por la ganancia del asteroide vendido
      ganancia_no_haciendo_nada = astroVoidAux(j-1, c)
      return max(ganancia_comprando, ganancia_vendiendo, ganancia_no_haciendo_nada)

  return astroVoidAux(n_dias-1, 0)

In [ ]:
p = [3,2,5,6]
p2 = [3,6,10]

print(astroVoid(p))
print(astroVoid(p2))

6
7


In [ ]:
import numpy as np

def astroVoidMemo(precios):
  n_dias = len(precios)

  # Creo la memoria
  M = np.zeros((n_dias, n_dias+1))

  # Inicializo los elementos con Nan
  M.fill(np.nan)

  def astroVoidMemoAux(j, c):
    nonlocal precios, M
    if c < 0 or c > j+1:
      return -float('inf')

    elif j==0:
      if c==1:
        return - precios[j]
      else:
        return 0

    else:
      # Si no hay valor calculado en la memoria lo calculo
      if np.isnan(M[j, c]):
        ganancia_comprando= astroVoidMemoAux(j-1, c-1) - precios[j]    # resto p[j] por el coste del asteroide comprado
        ganancia_vendiendo= astroVoidMemoAux(j-1, c+1) + precios[j]    # sumo p[j] por la ganancia del asteroide vendido
        ganancia_no_haciendo_nada = astroVoidMemoAux(j-1, c)
        M[j, c] = max(ganancia_comprando, ganancia_vendiendo, ganancia_no_haciendo_nada)

      # Devuelvo valor de memoria
      return M[j, c]

  return astroVoidMemoAux(n_dias-1, 0)

In [ ]:
p = [3,2,5,6]
p2 = [3,6,10]

print(astroVoidMemo(p))
print(astroVoidMemo(p2))

6.0
7.0


La complejidad del algoritmo de PD top-down es de O(n^2) siendo n= días, pues en este caso como se puede comprar máximo 1 asteroide por día la cantidad máxima que se puede tener de asteroides está acotada por la cantidad de los días (no se puede tener más asteroides que la cantidad de días que transcurrieron)

# 8. CortesEconómicos
---
Debemos cortar una vara de madera en varios lugares predeterminados. Sabemos que el costo de realizar un corte en una madera de longitud ℓ es ℓ (y luego de realizar ese corte quedarán 2 varas de longitudes que sumarán ℓ). Por ejemplo, si tenemos una vara de longitud 10 metros que debe ser cortada a los 2, 4 y 7 metros desde un extremo, entonces los cortes se pueden realizar, entre otras maneras, de las siguientes formas:

- Primero cortar en la posición 2, después en la 4 y después en la 7. Esta resulta en un costo de 10 + 8 + 6 = 24 porque el primer corte se hizo en una vara de longitud 10 metros, el segundo en una de 8 metros y el último en una de 6 metros.
- Cortar primero donde dice 4, después donde dice 2, y finalmente donde dice 7, con un costo
de 10 + 4 + 6 = 20, que es menor.

Queremos encontrar el mínimo costo posible de cortar una vara de longitud ℓ.

---

a) Convencerse de que el mínimo costo de cortar una vara que abarca desde i hasta j con el conjunto C de lugares de corte es j − i mas el mínimo, para todo lugar de corte c entre i y
j, de la suma entre el mínimo costo desde i hasta c y el mínimo costo desde c hasta j.

b) Escribir matemáticamente una formulación recursiva basada en a). Explicar su semántica e indicar cuáles serían los parámetros para resolver el problema.



**Res**:

\begin{align}
\ corte(j, i) = j-i~+~min\{~corte(i, c) + corte(c, j)~\}  ~~~~~~~~~~~ ~\forall~ i \leq c \leq j
\end{align}


Los parámetros son:

- j: medida del comienzo del palo
- i: medida del final del palo
(tal que al hacer j-i nos da la distancia del palo actual ℓ)
- c: medida del corte a realizar

Además tendrá que haber una variable externa C que contenga las medidas de los cortes a realizar (ci ∈ C )


---
c) Diseñar un algoritmo de PD y dar su complejidad temporal y espacial auxiliar. Comparar cómo resultaría un enfoque top-down con uno bottom-up.


In [ ]:
import numpy as np

def cortesEconomicos(C):
  n_cortes = len(C)
  largo_palo = C[-1]

  # Creo la memoria
  M = np.zeros((n_cortes, n_cortes))

  # Inicializo los elementos con Nan
  M.fill(np.nan)

  def cortesAux(i, j):
    nonlocal M

    inicio = C.index(i)
    final = C.index(j)

    # Caso base: ya no hay cortes intermedios en el segmento
    if final-inicio <= 1:
      # Devuelvo 0 porque no hay que hacer más cortes
      return 0

    else:
      # De acá voy a tomar el mínimo después
      candidatos = []

      # Para cada marca a cortar entre i y j
      for c in C[inicio+1 : final]:

        # Tomo el índice de corte en C
        corte = C.index(c)

        if np.isnan(M[inicio, corte]):
          M[inicio, corte] = cortesAux(i, c)    # cortesAux la vuelvo a llamar con los valores de i, corte y j, no con los índices

        if np.isnan(M[corte, final]):
          M[corte, final] = cortesAux(c, j)

        candidatos.append(M[inicio, corte] + M[corte, final])

      return j-i + min(candidatos)

  # Llamo y devuelvo la función recursiva:
  return cortesAux(0, largo_palo)

In [ ]:
# Ej: vara de longitud 10 metros que debe ser cortada a los 2, 4 y 7  metros
C = [0, 2, 4, 7, 10]

print(cortesEconomicos(C))

20.0


In [ ]:
# En esta versión i y j son directamente los índices.

import numpy as np

def cortesEconomicos2(C, largo_palo):

  # Le agrego los extremos: 0 al comienzo y largo_palo al final
  C.insert(0, 0)
  C.append(largo_palo)

  n = len(C)

  # Creo la memoria
  M = np.zeros((n, n))

  # Inicializo los elementos con Nan
  M.fill(np.nan)

  def cortesAux(i, j):
    nonlocal M

    # Caso base: ya no hay cortes intermedios en el segmento
    if j-i <= 1:
      # Devuelvo 0 porque no hay que hacer más cortes
      return 0

    else:
      # De acá voy a tomar el mínimo después
      candidatos = []

      # Para cada marca a cortar entre C[i] y C[j]  (for corte in C[i+1 : j])
      for c in range(i+1, j):

        if np.isnan(M[i, c]):
          M[i, c] = cortesAux(i, c)    # cortesAux la vuelvo a llamar con los valores de i, corte y j, no con los índices

        if np.isnan(M[c, j]):
          M[c, j] = cortesAux(c, j)

        candidatos.append(M[i, c] + M[c, j])

      return C[j]-C[i] + min(candidatos)

  # Llamo y devuelvo la función recursiva:

  return cortesAux(0, n-1), '\n',  M    # n-1 = índice de largo_palo


In [ ]:
# Ej: vara de longitud 10 metros que debe ser cortada a los 2, 4 y 7  metros
C2 = [2, 4, 7]

print(cortesEconomicos2(C2, 10))

(20.0, '\n', array([[nan,  0.,  4., 11., nan],
       [nan, nan,  0.,  5., 13.],
       [nan, nan, nan,  0.,  6.],
       [nan, nan, nan, nan,  0.],
       [nan, nan, nan, nan, nan]]))


In [ ]:
# Bottom-up
import numpy as np

def memoria(C):

  n= len(C)

  # Creo la memoria
  M = np.zeros((n, n))

  # Los pares i y j donde j-i<=1 son el caso base se quedan en 0
  # Lleno los que no:
  for k in range(2, n):   # para cada valor de distancia posible a partir de >1
    for i in range(n):
      if i+k < n:
        j= i+k
        candidatos = []

        # Para cada marca a cortar entre C[i] y C[j]  (for corte in C[i+1 : j])
        for c in range(i+1, j):
          # Cuando paso por acá, ya debería tener los M[i, c] y M[c, j] calculados porque ya calculé las distancias menores a k
          candidatos.append(M[i, c] + M[c, j])

        M[i, j] = C[j]-C[i] + min(candidatos)

  return M

def cortesEconomicos2(C, largo_palo):

  # Le agrego los extremos: 0 al comienzo y largo_palo al final
  C.insert(0, 0)
  C.append(largo_palo)

  # Creo y lleno la memoria
  M = memoria(C)

  # Devuelvo el mínimo con i=0, j=20
  return M[0, len(C)-1]




In [ ]:
C2 = [2, 4, 7]

print(cortesEconomicos2(C2, 10))

(20.0, array([[ 0.,  0.,  4., 11., 20.],
       [ 0.,  0.,  0.,  5., 13.],
       [ 0.,  0.,  0.,  0.,  6.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]]))


In [ ]:



  def cortesAux(i, j):
    nonlocal M

    # Caso base: ya no hay cortes intermedios en el segmento
    if j-i <= 1:
      # Devuelvo 0 porque no hay que hacer más cortes
      return 0

    else:
      # De acá voy a tomar el mínimo después
      candidatos = []

      # Para cada marca a cortar entre C[i] y C[j]  (for corte in C[i+1 : j])
      for c in range(i+1, j):
          M[i, c] = cortesAux(i, c)    # cortesAux la vuelvo a llamar con los valores de i, corte y j, no con los índices
          M[c, j] = cortesAux(c, j)

        candidatos.append(M[i, c] + M[c, j])

      return C[j]-C[i] + min(candidatos)

  # Llamo y devuelvo la función recursiva:
  return cortesAux(0, n-1)    # n-1 = índice de largo_palo

# 9. Travesía Vital
Hay un terreno, que podemos pensarlo como una grilla de m filas y n columnas, con trampas y pociones. Queremos llegar de la esquina superior izquierda hasta la inferior derecha, y desde cada casilla sólo podemos movernos a la casilla de la derecha o a la de abajo. Cada casilla i,j tiene un número entero Ai,j que nos modificará el nivel de vida sumándonos el número Ai,j (si es negativo, nos va a restar |Ai,j| de vida). Queremos saber el mínimo nivel de vida con el que
debemos comenzar tal que haya un camino posible de modo que en todo momento nuestro nivel de vida sea al menos 1.

Por ejemplo, si tenemos la grilla:

\begin{align}
\ A =
\begin{bmatrix}
-2 & -3 & 3 \\\\
-5 & -10 & 1 \\\\
10 & 30 & -5 \\\\
\end{bmatrix}
\end{align}


el mínimo nivel de vida con el que podemos comenzar es 7 porque podemos realizar el camino que va todo a la derecha y todo abajo.

a) Pensar la idea de un algoritmo de backtracking (no hace falta escribirlo).

b) Convencerse de que, excepto que estemos en los límites del terreno, la mínima vida necesaria al llegar a la posición i, j es el resultado de restar al mínimo entre la mínima vida necesaria en i + 1, j y aquella en i, j + 1, el valor Ai,j , salvo que eso fuera menor o igual que 0, en cuyo caso sería 1.

c) Escribir una formulación recursiva basada en b). Explicar su semántica e indicar cuáles serían los parámetros para resolver el problema.

d) Diseñar un algoritmo de PD y dar su complejidad temporal y espacial auxiliar. Comparar cómo resultaría un enfoque top-down con uno bottom-up.

e) Dar un algoritmo bottom-up cuya complejidad temporal sea O(m · n) y la espacial auxiliar
sea O(m´ın(m, n)).

---
**Planteo**

Básicamente tenemos que hallar el camino mínimo, pues la vida que necesitamos va a ser el mínimo + 1 (porque tengo que tener en todo momento al menos 1)

a) Hacerlo con backtracking sería calcular todos los caminos posibles y tomar el mínimo.

b) Claro, busco cuál es el camino mínimo del camino avanzando uno por arriba o por abajo, y a eso le resto Aij porque ese mínimo tiene contado el haber sumado el valor en Aij a la vida.

c)

minRecorrido(i, j, M) = \begin{cases}
\min\{~minRecorrido(i+1, j, M),~ minRecorrido(i, j+1, M)\} - A_{i,j} & \text{si } i \leq m ~ and ~ j\leq n \\
minRecorrido(i, j+1, M)- A_{i,j}\ & \text{si } i = m  ~ and ~ j\leq n  \\
minRecorrido(i+1, j, M)- A_{i,j}\ & \text{si } j = n  ~ and ~ i\leq m  \\
-A_{i,j} + 1 & \text{si } i=m ~ and ~ j = n \\
1  & \text{si }~ minRecorrido() - A_{i,j} \leq 0
\end{cases}


In [ ]:
import numpy as np

M = np.array([[-2,-3,3],[-5,-10,1], [10, 30, -5]])

print(M)

[[ -2  -3   3]
 [ -5 -10   1]
 [ 10  30  -5]]


In [ ]:
print(len(M[0])-1)

2


In [ ]:
def minRecorrido(i, j, M):

  # Caso base: llegué a la última casilla
  if i== len(M)-1 and j== len(M[0])-1:
    return -M[i,j]+1

  # Caso llegué al extremo inferior (última fila)
  elif i== len(M)-1 and j<= len(M[0])-1 :
    min_ = minRecorrido(i, j+1, M) -M[i, j]
    # Si la resta da igual o menor a 0 (es decir, con cualquier vida va a estar bien gracias a lo que le sumo con el casillero Aij), devuelvo 1
    if min_<=0:
      return 1
    else:
      return min_

  elif j== len(M[0])-1 and i<= len(M)-1:
    min_ = minRecorrido(i+1, j, M) -M[i, j]
    # Si la resta da igual o menor a 0 (es decir, con cualquier vida va a estar bien gracias a lo que le sumo con el casillero Aij), devuelvo 1
    if min_<=0:
      return 1
    else:
      return min_


  else:
    min_ = min(minRecorrido(i+1, j, M), minRecorrido(i, j+1, M)) -M[i, j]
    # Si la resta da igual o menor a 0 (es decir, con cualquier vida va a estar bien gracias a lo que le sumo con el casillero Aij), devuelvo 1
    if min_<=0:
      return 1
    else:
      return min_

In [ ]:
print(minRecorrido(0,0,M))

7


N° llamados recursivos del algoritmo:
Casos extremos (lleno al límite de una columna o fila): 1 llamada (hacia abajo o hacia a la derecha)
Caso base (casilla final): 0 llamadas
Caso 'normal': 2 llamadas (hacia abajo Y hacia a la derecha)

\# casos extremos: (m-1)+(n-1) = m+n-2
\# casos base: 1
\# casos normales: (n-1)*(m-1)

Entonces # llamados= O((n-1)\*(m-1)\*2) + O((m + n - 2)*1) + 0 = O(2nm - n - m) = O(nm)

In [ ]:
# Ahora bottom up

# En realidad el algoritmo creo que es similar. El anterior hace algo tipo bottom-up, ya que va directamente al caso base y empieza a construir desde ahí.
# O quizás no es lo mismo porque el anterior va hasta el caso base pero desde una misma rama, y luego desde otras, mientras que bottom up iría al caso base
# e iría construyendo el siguiente nivel (de todas las ramas) y después el siguiente, y así

# Creo y calculo matriz de "costos mínimos de vida por casillero" (va guardando las vidas mínimas necesarias para cada casillero)
M_costos = np.zeros((len(M), len(M[0])))

n= len(M_costos)
m= len(M_costos[0])

# Voy de m a 0 y de n a 0
for i in range(n-1, -1, -1):
  for j in range(m-1,-1,-1):
    if i<n-1 and j<n-1:
      min_ = min(M_costos[i+1, j], M_costos[i, j+1]) - M[i, j]
      M_costos[i,j] = 1 if min_<=0 else min_

    elif i==n-1 and j==m-1:
      M_costos[i,j] = -M[i,j] + 1

    elif j==n-1:
      min_ = M_costos[i+1, j] - M[i, j]
      M_costos[i,j] = 1 if min_<=0 else min_

    else:  # Caso i==n-1
      min_ = M_costos[i, j+1] - M[i, j]
      M_costos[i,j] = 1 if min_<=0 else min_

print(M_costos)



[[ 7.  5.  2.]
 [ 6. 11.  5.]
 [ 1.  1.  6.]]


Ufa, me pedía complejidad espacial O(min(n,m)) ni idea ahí.

Supongo que la estructura tendría que ir guardando los costos solo para el camino mínimo. Algo así como ir guardando en cada iteración, el mínimo entre haber ido por la derecha y haber ido por abajo.

In [ ]:
M_costos = np.zeros(5)   # min(len(M), len(M[0]))+2

n= len(M)
m= len(M[0])

# Voy de m a 0 y de n a 0
i= n-1
j= m-1
k= len(M_costos)-1

while i>=0 and j>=0 and 0<=k:

  if k== len(M_costos)-1:
    print(k)
    M_costos[k] = -M[i,j] + 1
    print(M_costos[k])
    k -= 1

  if i>0 and j>0:

    if M_costos[k+1] - M[i-1,j] < M_costos[k+1] - M[i,j-1]:  # si el mínimo está yendo hacia arriba
      min_ = M_costos[k+1] - M[i-1,j]
      print("me fui por arriba", k)
      M_costos[k] = 1 if min_ <=0 else min_
      print(M_costos[k])
      i -=1     # actualizo coordenada vertical
      k -=1
      continue

    else:
      min_= M_costos[k+1] - M[i,j-1]                                  # si el mínimo está yendo hacia izq
      print("me fui por izq", k)
      M_costos[k] = 1 if min_ <= 0 else min_
      print(M_costos[k])
      j -=1     # actualizo coordenada horizontal
      k -=1
      continue

  elif i==0 and j==0:
    min_ = M_costos[k+1] - M[i][j]
    M_costos[k] = 1 if min_ <= 0 else min_
    break

  elif i==0:
    min_ = M_costos[k+1] - M[i,j-1]
    print(k)
    M_costos[k] = 1 if min_<=0 else min_   # no me queda otra que ir hacia la izq
    print(M_costos[k])
    j-=1
    k -=1
    continue

  elif j==0:
    min_ = M_costos[k+1] - M[i-1,j]
    print(k)
    M_costos[k] = 1 if min_<=0 else min_    # no me queda otra que ir hacia arriba
    print(M_costos[k])
    i-= 1
    k -=1
    continue

print(M_costos)

4
6.0
me fui por izq 3
1.0
me fui por izq 2
1.0
1
6.0
0
8.0
[8. 6. 1. 1. 6.]


In [ ]:
# ESTO ES RE FAIL, OLVÍDENLO

[7. 5. 2. 5. 4.]


## 10. PilaCauta
Tenemos cajas numeradas de 1 a N, todas de iguales dimensiones. Queremos encontrar la máxima cantidad de cajas que pueden apilarse en una única pila cumpliendo que:
- sólo puede haber una caja apoyada directamente sobre otra;
- las cajas de la pila deben estar ordenadas crecientemente por número, de abajo para arriba;
- cada caja i tiene un peso w_i y un soporte s_i, y el peso total de las cajas que están arriba de otra no debe exceder el soporte de esa otra.

Si tenemos los pesos w = [19, 7, 5, 6, 1] y los soportes s = [15, 13, 7, 8, 2] (la caja 1 tiene peso 19 y soporte 15, la caja 2 tiene peso 7 y soporte 13, etc.), entonces la respuesta es 4. Por ejemplo,
pueden apilarse de la forma 1-2-3-5 o 1-2-4-5 (donde la izquierda es más abajo), entre otras opciones.

a) Pensar la idea de un algoritmo de backtracking (no hace falta escribirlo).

b) Escribir una formulación recursiva que sea la base de un algoritmo de PD. Explicar su semántica e indicar cuáles serían los parámetros para resolver el problema.

c) Diseñar un algoritmo de PD y dar su complejidad temporal y espacial auxiliar. Comparar cómo resultaría un enfoque top-down con uno bottom-up.

d) (Opcional) Formalizar el problema y demostrar que la función recursiva es correcta.


a) el algoritmo de backtracking consistiría en generar todas las pilas posibles, descartando aquellas que dejan de cumplir los requerimientos y luego quedándome con la que mayor cantidad de cajas tenga.

b)
El algoritmo de PD puede consistir en, en cada instancia en la que tengo que decidir si agrego la caja o no, fijarme la decisión que me conduce a la mayor cantidad de cajas posibles. Esto es, quedándome con el max de cajas entre la pila agregando la caja y no agregando la caja.


pilaCauta(i, j, M) = \begin{cases}
1 + max\{~pilaCauta(peso\_total + peso[i], i-1),~pilaCauta(peso\_total, i-1)\}  & \text{si i se aguanta el peso de las de arriba}  \\
0 & \text{si no se aguanta el peso}  \\
\end{cases}

Creo que esto es simplemente backtracking :/ En qué momento sucede la repetición de problemas? Podría ser cuando llego a la j-ésima caja, pedir que me devuelva la mayor cantidad de cajas posibles a partir de esa caja, pero está la limitación de que la caja de abajo tiene que soportar ese peso, entonces en realidad cada entrada es única, y quizás "la mayor cantidad de cajas a partir de la j-ésima caja" no es solución válida porque la caja de abajo no la soporta, pero una solución que se descartó por no ser la mayor cantidad sí es válida.
Pienso en un ejemplo más chico|||

enfoque bottom up
primero filtrar por las opciones que soporta la caja i y luego seleccionar la de mayor cantidad de cajas.

enfoque top-down
Para hacerlo PD bastaría con agregar una memoria que me vaya guardando el peso acumulado desde la caja de la caja j hasta la caja i (O bien la diferencia entre el soporte máximo y el peso acumulado). En el momento que alguna de las cajas supera su soporte máximo, se descarta la solución. (Pero y si hay cajas entre j e i que decido no apilar??)

In [ ]:
def maxCajasApiladas(w, s):
    n = len(w)
    # Creamos una lista para almacenar el peso total acumulado de todas las cajas colocadas sobre cada caja
    peso_total = [w[i] for i in range(n)]
    # Creamos una lista para almacenar la cantidad máxima de cajas apiladas hasta la caja i
    max_cajas = [1] * n

    # Inicializamos el máximo con la cantidad de cajas en la pila actual
    max_actual = 1
    # Iteramos sobre todas las cajas
    for i in range(n-1,-1,-1):
        cajas=1
        # Iteramos sobre las cajas anteriores para encontrar la máxima cantidad de cajas que pueden apilarse
        for j in range(i-1,-1,-1):
            # Verificamos si la caja i puede apilarse sobre la caja j sin exceder su soporte
            if s[j] >= peso_total[i]:
                # Actualizamos el peso total acumulado de la caja i
                peso_total[i] += w[j]
                cajas+=1
                # Actualizamos el máximo si la cantidad de cajas apiladas hasta j + 1 es mayor que el máximo actual
                max_actual = max(max_cajas[i], cajas)
        # Almacenamos el máximo en la lista
        max_cajas[i] = max_actual

    # Devolvemos el máximo de la lista
    return max(max_cajas)

# Ejemplo de uso
w = [19, 7, 5, 6, 3]
s = [15, 13, 7, 8, 2]
print(maxCajasApiladas(w, s))  # Output: 4

3


## 11. OperacionesSeq
Sea v = (v1, v2, . . . vn) un vector de números naturales, y sea w ∈ N. Se desea intercalar entre los elementos de v las operaciones + (suma), × (multiplicación) y ↑ (potenciación) de tal manera que al evaluar la expresión obtenida el resultado sea w.

 Para evaluar la expresión se opera de izquierda a derecha ignorando la precedencia de los operadores. Por ejemplo, si v = (3, 1, 5, 2, 1),
y las operaciones elegidas son +, ×, ↑ y × (en ese orden), la expresión obtenida es 3+1×5 ↑ 2×1, que se evalúa como (((3 + 1) × 5) ↑ 2) × 1 = 400.


a) Escribir una formulación recursiva que sea la base de un algoritmo de PD que, dados v y w, encuentre una secuencia de operaciones como la deseada, en caso de que tal secuencia exista.
Explicar su semántica e indicar cuáles serían los parámetros para resolver el problema.

b) Diseñar un algoritmo basado en PD con la formulación de a) y dar su complejidad temporal
y espacial auxiliar. Comparar cómo resultaría un enfoque top-down con uno bottom-up.

c) (Opcional) Formalizar el problema y demostrar que la función recursiva es correcta

Acá me pasa lo mismo. Sé cómo hacerlo con backtracking y sé que puedo ir acotando según si el cálculo se pasa de w o no, pero no logro identificar la superposición de problemas como para usar PD.

Qué datos puedo ir guardando en una estructura tal que vuelva a necesitar esa info? Si lo que busco no es el mínimo o máximo, y encima nisiquiera puedo repetir operadores.
Se me ocurre algo así como guardar el resultado de intercalar una subsecuencia de las operaciones con una subsecuencia de números y a partir de ahí construir con lo restante.

Pero sería equivalente a ir probando variantes a partir de una misma subsecuencia (como las ramificaciones del backtracking), o no?